
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3


test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: utf8
  database: d48scs1aa1i0p6
  pool: 5432
  username: fbtvbqqkamfdgt   #-> *** data from heroku's postgres user details page
  password: YO7aoMMlX8jz4HnEqaxylKKYNz
  host: ec2-107-20-234-127.compute-1.amazonaws.com
