
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3


test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: utf8
  database: d63g7d4m154gvh
  pool: 5432
  username: kawrfcedajnlpn  #-> *** data from heroku's postgres user details page
  password: SphxwHxRvqVot0xksQiQkFmVUS
  host: ec2-54-197-241-97.compute-1.amazonaws.com
